title: Sherwin Nikolai Saga
#logo: /assets/img/imageurl.png
description: A motivated Computer Science student with a strong grasp of
programming concepts and zeal for software development.
Proactive and problem solving oriented, I am actively seeking
internship opportunities to apply my theoretical knowledge and
acquire practical industry experience.
#show_downloads: true
theme: jekyll-theme-minimal
